// automatically generated by the FlatBuffers compiler, do not modify

package com.tracker.shared.flatbuf;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

import java.nio.ByteBuffer;

@SuppressWarnings("unused")
public final class MarkersFlat extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MarkersFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double lat() { return bb.getDouble(bb_pos + 0); }
  public double lon() { return bb.getDouble(bb_pos + 8); }
  public int colour() { return bb.getInt(bb_pos + 16); }

  public static int createMarkers(FlatBufferBuilder builder, double lat, double lon, int colour) {
    builder.prep(8, 24);
    builder.pad(4);
    builder.putInt(colour);
    builder.putDouble(lon);
    builder.putDouble(lat);
    return builder.offset();
  }
}

