// automatically generated by the FlatBuffers compiler, do not modify

package com.tracker.shared.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PolylineFlat extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public PolylineFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double lat() { return bb.getDouble(bb_pos + 0); }
  public double lon() { return bb.getDouble(bb_pos + 8); }

  public static int createPolylineFlat(FlatBufferBuilder builder, double lat, double lon) {
    builder.prep(8, 16);
    builder.putDouble(lon);
    builder.putDouble(lat);
    return builder.offset();
  }
}

