// automatically generated by the FlatBuffers compiler, do not modify

package com.tracker.shared.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SplitsFlat extends Table {
  public static SplitsFlat getRootAsSplitsFlat(ByteBuffer _bb) { return getRootAsSplitsFlat(_bb, new SplitsFlat()); }
  public static SplitsFlat getRootAsSplitsFlat(ByteBuffer _bb, SplitsFlat obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SplitsFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SplitFlat splits(int j) { return splits(new SplitFlat(), j); }
  public SplitFlat splits(SplitFlat obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o) + j * 24, bb) : null; }
  public int splitsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createSplitsFlat(FlatBufferBuilder builder,
      int splitsOffset) {
    builder.startObject(1);
    SplitsFlat.addSplits(builder, splitsOffset);
    return SplitsFlat.endSplitsFlat(builder);
  }

  public static void startSplitsFlat(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSplits(FlatBufferBuilder builder, int splitsOffset) { builder.addOffset(0, splitsOffset, 0); }
  public static void startSplitsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(24, numElems, 8); }
  public static int endSplitsFlat(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

