// automatically generated by the FlatBuffers compiler, do not modify

package com.tracker.shared.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SportActivityFlat extends Table {
  public static SportActivityFlat getRootAsSportActivityFlat(ByteBuffer _bb) { return getRootAsSportActivityFlat(_bb, new SportActivityFlat()); }
  public static SportActivityFlat getRootAsSportActivityFlat(ByteBuffer _bb, SportActivityFlat obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SportActivityFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String activity() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer activityAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer activityInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public double distance() { int o = __offset(8); return o != 0 ? bb.getDouble(o + bb_pos) : -1.0; }
  public long startTimestamp() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public long endTimestamp() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public long duration() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public int calories() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : -1; }
  public long steps() { int o = __offset(18); return o != 0 ? bb.getLong(o + bb_pos) : -1L; }
  public SplitsFlat splits() { return splits(new SplitsFlat()); }
  public SplitsFlat splits(SplitsFlat obj) { int o = __offset(20); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public SportActivityMapFlat sportActivityMap() { return sportActivityMap(new SportActivityMapFlat()); }
  public SportActivityMapFlat sportActivityMap(SportActivityMapFlat obj) { int o = __offset(22); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public int type() { int o = __offset(24); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long lastModified() { int o = __offset(26); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createSportActivityFlat(FlatBufferBuilder builder,
      int idOffset,
      int activityOffset,
      double distance,
      long startTimestamp,
      long endTimestamp,
      long duration,
      int calories,
      long steps,
      int splitsOffset,
      int sportActivityMapOffset,
      int type,
      long last_modified) {
    builder.startObject(12);
    SportActivityFlat.addLastModified(builder, last_modified);
    SportActivityFlat.addSteps(builder, steps);
    SportActivityFlat.addDuration(builder, duration);
    SportActivityFlat.addEndTimestamp(builder, endTimestamp);
    SportActivityFlat.addStartTimestamp(builder, startTimestamp);
    SportActivityFlat.addDistance(builder, distance);
    SportActivityFlat.addType(builder, type);
    SportActivityFlat.addSportActivityMap(builder, sportActivityMapOffset);
    SportActivityFlat.addSplits(builder, splitsOffset);
    SportActivityFlat.addCalories(builder, calories);
    SportActivityFlat.addActivity(builder, activityOffset);
    SportActivityFlat.addId(builder, idOffset);
    return SportActivityFlat.endSportActivityFlat(builder);
  }

  public static void startSportActivityFlat(FlatBufferBuilder builder) { builder.startObject(12); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addActivity(FlatBufferBuilder builder, int activityOffset) { builder.addOffset(1, activityOffset, 0); }
  public static void addDistance(FlatBufferBuilder builder, double distance) { builder.addDouble(2, distance, -1.0); }
  public static void addStartTimestamp(FlatBufferBuilder builder, long startTimestamp) { builder.addLong(3, startTimestamp, -1L); }
  public static void addEndTimestamp(FlatBufferBuilder builder, long endTimestamp) { builder.addLong(4, endTimestamp, -1L); }
  public static void addDuration(FlatBufferBuilder builder, long duration) { builder.addLong(5, duration, -1L); }
  public static void addCalories(FlatBufferBuilder builder, int calories) { builder.addInt(6, calories, -1); }
  public static void addSteps(FlatBufferBuilder builder, long steps) { builder.addLong(7, steps, -1L); }
  public static void addSplits(FlatBufferBuilder builder, int splitsOffset) { builder.addOffset(8, splitsOffset, 0); }
  public static void addSportActivityMap(FlatBufferBuilder builder, int sportActivityMapOffset) { builder.addOffset(9, sportActivityMapOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(10, type, 0); }
  public static void addLastModified(FlatBufferBuilder builder, long lastModified) { builder.addLong(11, lastModified, 0L); }
  public static int endSportActivityFlat(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishSportActivityFlatBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedSportActivityFlatBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

