// automatically generated by the FlatBuffers compiler, do not modify

package com.tracker.shared.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SportActivityWithOwnerFlat extends Table {
  public static SportActivityWithOwnerFlat getRootAsSportActivityWithOwnerFlat(ByteBuffer _bb) { return getRootAsSportActivityWithOwnerFlat(_bb, new SportActivityWithOwnerFlat()); }
  public static SportActivityWithOwnerFlat getRootAsSportActivityWithOwnerFlat(ByteBuffer _bb, SportActivityWithOwnerFlat obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SportActivityWithOwnerFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String activity() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer activityAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public double distance() { int o = __offset(8); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public int duration() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createSportActivityWithOwnerFlat(FlatBufferBuilder builder,
      int nameOffset,
      int activityOffset,
      double distance,
      int duration) {
    builder.startObject(4);
    SportActivityWithOwnerFlat.addDistance(builder, distance);
    SportActivityWithOwnerFlat.addDuration(builder, duration);
    SportActivityWithOwnerFlat.addActivity(builder, activityOffset);
    SportActivityWithOwnerFlat.addName(builder, nameOffset);
    return SportActivityWithOwnerFlat.endSportActivityWithOwnerFlat(builder);
  }

  public static void startSportActivityWithOwnerFlat(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addActivity(FlatBufferBuilder builder, int activityOffset) { builder.addOffset(1, activityOffset, 0); }
  public static void addDistance(FlatBufferBuilder builder, double distance) { builder.addDouble(2, distance, 0.0); }
  public static void addDuration(FlatBufferBuilder builder, int duration) { builder.addInt(3, duration, 0); }
  public static int endSportActivityWithOwnerFlat(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

