// automatically generated by the FlatBuffers compiler, do not modify

package com.tracker.shared.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class WeightsFlat extends Table {
  public static WeightsFlat getRootAsWeightsFlat(ByteBuffer _bb) { return getRootAsWeightsFlat(_bb, new WeightsFlat()); }
  public static WeightsFlat getRootAsWeightsFlat(ByteBuffer _bb, WeightsFlat obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public WeightsFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public WeightFlat weights(int j) { return weights(new WeightFlat(), j); }
  public WeightFlat weights(WeightFlat obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int weightsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createWeightsFlat(FlatBufferBuilder builder,
      int weightsOffset) {
    builder.startObject(1);
    WeightsFlat.addWeights(builder, weightsOffset);
    return WeightsFlat.endWeightsFlat(builder);
  }

  public static void startWeightsFlat(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addWeights(FlatBufferBuilder builder, int weightsOffset) { builder.addOffset(0, weightsOffset, 0); }
  public static int createWeightsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startWeightsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endWeightsFlat(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

